spring:
  datasource:
    url: jdbc:postgresql://dpg-cnqff94f7o1s73cio640-a.oregon-postgres.render.com/lwldb
    username: dbuser
    password: F38RLKaGVaqh1s3pmWgmytKUUIF6pTc1
  jpa:
      hibernate:
        ddl-auto: update
      properties:
          hibernate:
            show_sql: true
            format_sql: true

